# Generated by Django 5.2.6 on 2025-09-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_log_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='type',
            field=models.CharField(choices=[('print', 'Print/eBook'), ('comicbook', 'Comicbook'), ('audiobook', 'AudioBook'), ('podcast', 'Podcast')], max_length=250),
        ),
    ]
