# Generated by Django 5.2.6 on 2025-09-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_log_cover_alter_log_notes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='log',
            name='cover',
        ),
        migrations.AddField(
            model_name='log',
            name='cover_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
