# Generated by Django 5.2.6 on 2025-09-18 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_title_log_name_remove_log_cover_log_cover_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='name',
            new_name='title',
        ),
    ]
