# Generated by Django 5.2.6 on 2025-09-18 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_rename_name_log_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='cover_url',
            new_name='image_url',
        ),
    ]
